#pragma checksum "..\AttachConfigMethodView.xaml" "{406ea660-64cf-4c82-b6f0-42d48172a799}" "DFC138B3ED6586A51D871B23C44EF9F7"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using JetBrains.UI;
using JetBrains.UI.Avalon;
using JetBrains.UI.Controls;
using JetBrains.UI.Icons;
using JetBrains.UI.Resources;
using ResharperBuild.AttachAction;
using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;


namespace ResharperBuild.AttachAction {
    
    
    /// <summary>
    /// AttachConfigMethodView
    /// </summary>
    public partial class AttachConfigMethodView : System.Windows.Controls.StackPanel, System.Windows.Markup.IComponentConnector {
        
        
        #line 16 "..\AttachConfigMethodView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox ExecutablePath;
        
        #line default
        #line hidden
        
        
        #line 32 "..\AttachConfigMethodView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox WorkingDirectory;
        
        #line default
        #line hidden
        
        
        #line 42 "..\AttachConfigMethodView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox CommandLine;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/ResharperBuild.AttachAction;component/attachconfigmethodview.xaml", System.UriKind.Relative);
            
            #line 1 "..\AttachConfigMethodView.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            this.ExecutablePath = ((System.Windows.Controls.TextBox)(target));
            
            #line 16 "..\AttachConfigMethodView.xaml"
            this.ExecutablePath.GotKeyboardFocus += new System.Windows.Input.KeyboardFocusChangedEventHandler(this.SelectOnKeyboardFocus);
            
            #line default
            #line hidden
            return;
            case 2:
            this.WorkingDirectory = ((System.Windows.Controls.TextBox)(target));
            
            #line 32 "..\AttachConfigMethodView.xaml"
            this.WorkingDirectory.GotKeyboardFocus += new System.Windows.Input.KeyboardFocusChangedEventHandler(this.SelectOnKeyboardFocus);
            
            #line default
            #line hidden
            return;
            case 3:
            this.CommandLine = ((System.Windows.Controls.TextBox)(target));
            
            #line 42 "..\AttachConfigMethodView.xaml"
            this.CommandLine.GotKeyboardFocus += new System.Windows.Input.KeyboardFocusChangedEventHandler(this.SelectOnKeyboardFocus);
            
            #line default
            #line hidden
            return;
            }
            this._contentLoaded = true;
        }
    }
}

